### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by ibin7777** [GZPERRA/hide-teams-in-meet-popup#3]
Windows version 21h2 kb5007186
don't know how to check MS teams version, supposedly to be the newest
hope it helps

**Comment by sonicpro** [comment]
Neither works for me in Windows version 21h2 (OS Build 19044.2604), Teams Published by Microsoft Corporation
Version 1.0.

**Comment by sonicpro** [comment]
Neither works for me after Teams update to Teams Version 1.6.00.1381 (64-bit). Windows 10 21H2. Worked well before the update.

**Comment by GZPERRA** [comment]
@sonicpro I just tested it with Teams v1.6.00.1381 (64-bit) on Windows 21H2 (VM) and it's working. Please be aware that the tool uses the popup window **title** to find it and hide it, which must be in English.

**Comment by simonnageleisen** [comment]
For me it does not work anymore as well (Teams v1.6.00.1381) (21H2 build 19044.2604). 
The popup Window seems to have a new design, possibly using the meeting title as the window title ("Mittagspause" in attached screenshot), maybe that's the issue?
![2023-02-28 11_48_58](https://user-images.githubusercontent.com/26720265/221833420-34d03884-86b5-420d-80ce-d47e771dee9c.png)

**Comment by GZPERRA** [comment]
@sonicpro @simonnageleisen check the latest release.

**Comment by simonnageleisen** [comment]
@GZPERRA it does work again! Thank you!!! 
(Taskbar still shows the icon for the popup though, but the window itself is auto-hidden until I click on it in the taskbar)
![grafik](https://user-images.githubusercontent.com/26720265/223201899-92db003d-2980-4526-a506-cbfd5d992ffe.png)

**Comment by GZPERRA** [comment]
@simonnageleisen you're welcome. Check the latest release (v1.2.1-beta), it must fix that issue.

**Comment by simonnageleisen** [comment]
@GZPERRA unfortunately it still did not work for me with v1.2.1, still had the same behaviour as v1.2.0 (taskbar icon of popup window still visible).
I dowloaded the code and tried to build it myself, and got an error "LNK2019 unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)". Googled how to fix this and i found that I have to change the linker setting "SubSystem" in the Visual Studio Project Properties from "Console" to "Windows" (see picture). 
![grafik](https://user-images.githubusercontent.com/26720265/223426673-72f8eec8-62b9-4a64-9327-1582619ce153.png)
After I changed that, the code did compile, and also the tool now works as expect! (No taskbar icon anymore for hidden popup window).
To be honest I don't know how or why fixing the compile error also made the whole tool work all the sudden, but anyways, at least it works :)

**Comment by sonicpro** [comment]
> @sonicpro @simonnageleisen check the latest release.

@GZPERRA Not it hides the popup. Still have the issue with the taskbar button not hidden. I am going to apply the change to the build suggested by @simonnageleisen when I have spare time.

**Comment by sonicpro** [comment]
After changing Subsystem to Windows as it is suggested in https://github.com/GZPERRA/hide-teams-in-meet-popup/issues/3#issuecomment-1458118819 everything works as expected. I have only two buttons in the taskbar during the meeting, for non-closed to tray Teams and for the meeting itself. The popup dos not report itself.
![image](https://user-images.githubusercontent.com/5416927/224976629-1446369c-ae00-4408-8741-68abff58b770.png)

**Comment by GZPERRA** [comment]
Yes, Subsystem must be set to Windows, ~~unfortunately, Visual Studio doesn't save that setting in the project file~~ I don't know why your VisualStudio didn't pick it up from the project file. However, that shouldn't be the solution to the taskbar issue, as it doesn't affect that. I've downloaded the release and found out that I mistakenly re-uploaded the old version 😐. I would appreciate it if you can re-download the latest release and check if the issue has been fixed. Thanks for your feedback.
